steps:
# - name: 'print-branch-name'
#   id: 'branch-name'
#   entrypoint: 'sh'
#   args:
#   - '-c'
#   - |
#       echo "***********************"
#       echo "$BRANCH_NAME"
#       echo "***********************"

- name: 'clone-github-repo'
  id: 'clone-repo'
  entrypoint: 'git'
  args:
  - 'clone'
  - 'https://github.com/pRodriguez1630/terraform-infra-test.git'

- name: 'terraform-init'
  id: 'tf-init'
  entrypoint: 'terraform'
  args:
  - 'init'

- name: 'terraform-plan'
  id: 'tf-plan'
  entrypoint: 'terraform'
  args:
  - 'plan'

- name: 'terraform-apply'
  id: 'tf-apply'
  entrypoint: 'terraform'
  args:
  - 'apply'
  - '-auto-approve'