steps:
- id: 'clone repository'
  name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - 'https://github.com/pRodriguez1630/terraform-infra-test.git'

- id: 'branch name-2'
  name: gcr.io/cloud-builders/git
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      branch=main
      git checkout ${branch}
      echo "***********************"
      git branch --show-current
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
   branch=main
      if [ -d "terraform-infra-test/${branch}/" ]; then
        cd terraform-infra-test/${branch}
        terraform init
      else
        for dir in terraform-infra-test/*/
        do
          cd terraform-infra-test
        
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi

- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      branch=main
      if [ -d "terraform-infra-test/${branch}/" ]; then
        cd terraform-infra-test/${branch}
        terraform plan
      else
        for dir in terraform-infra-test/*/
        do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init
          terraform plan 
          cd ../../
        done
      fi

- id: 'tf check-existing-resources'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      branch=main
      if [ -d "terraform-infra-test/${branch}/" ]; then
        cd terraform-infra-test/${branch}
        # Consultar el estado actual de los recursos
        terraform show > current_state.tfstate
        # Analizar la salida para verificar si los recursos existen
        if grep -q "google_storage_bucket.mi_bucket" current_state.tfstate; then
          echo "Los recursos ya existen. No se requiere crearlos nuevamente."
          exit 0  # Salir sin ejecutar `terraform apply`
        else
          echo "Los recursos no existen. Se procederá con la creación."
        fi
      else
        echo "Directorio de Terraform no encontrado."
        exit 1
      fi

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      branch=main
      if [ -d "terraform-infra-test/${branch}/" ]; then
        cd terraform-infra-test/${branch}
        terraform apply -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '${branch}' does not represent an official environment."
        echo "*******************************************************************************"
        terraform apply -auto-approve
      fi
